server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fc_usuarios
    username: app_user
    password: kj5BEBMr
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
appDescription: "Food Court Users mngr"
appVersion: "1.0.0"
