server:
  servlet:
    context-path: /api/v1/mngr/users
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fc_usuarios
    username: app_user
    password: kj5BEBMr
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

application:
  security:
    jwt:
      rounds-encrypt: 12
      secret-key: "C2mBOVNCQY2xziZCCSSehBvzou1LIMj2h1AeUDi5sZ2UHVGHvMlO+eW1EIUPj+X92PTTJDBBLhS+6ftNMwjVeg=="
      expiration: 14400000
      refresh-token:
        expiration: 28800000

appDescription: "Food Court Users mngr"
appVersion: "1.0.0"
